FROM --platform=linux/amd64 node:16.16.0-alpine

ENV NODE_ENV=production

WORKDIR /opt/app

RUN mkdir ./prisma
COPY ./prisma ./prisma
COPY ./dist/apps/server .
COPY ./package.json .
COPY ./pnpm-lock.yaml .
COPY ./.npmrc .
COPY ./docker/server-entrypoint.sh .

RUN corepack enable && pnpm i --prod && pnpm prisma:generate

CMD ./server-entrypoint.sh
