FROM --platform=linux/amd64 node:16.16.0-alpine AS builder

WORKDIR /opt/app

COPY . .
RUN corepack enable
RUN pnpm install
RUN pnpm nx build frontend --prod


FROM --platform=linux/amd64 node:16.16.0-alpine

WORKDIR /opt/app
COPY --from=builder /opt/app/dist/apps/frontend .
RUN yarn

CMD yarn start
