services:
  postgres:
    container_name: nest-react-full-stack-postgres
    image: postgres:16.2-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: nest_blog
      POSTGRES_PASSWORD: nest_blog
      POSTGRES_DB: nest_blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-react-full-stack-server
    container_name: nest-react-full-stack-server
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - .env
    environment:
      VIRTUAL_PORT: 8081
      VIRTUAL_PATH: /api
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data:
